---
- name: "Ensure the Raspotify device name is set"
  become: true
  lineinfile:
    dest: /etc/raspotify/conf
    regexp: ^#?LIBRESPOT_NAME=
    line: "LIBRESPOT_NAME=\"{{ raspotify_device_name }}\""
  when: raspotify_device_name != None
  notify:
    - restart raspotify
- name: "Ensure the Raspotify audio backend is set"
  become: true
  lineinfile:
    dest: /etc/raspotify/conf
    regexp: ^#?LIBRESPOT_BACKEND=
    line: "LIBRESPOT_BACKEND={{ raspotify_audio_backend }}"
  when: raspotify_audio_backend != None
  notify:
    - restart raspotify
- name: "Ensure the Raspotify audio device is set"
  become: true
  lineinfile:
    dest: /etc/raspotify/conf
    regexp: ^#?LIBRESPOT_DEVICE=
    line: "LIBRESPOT_DEVICE={{ raspotify_audio_device }}"
  when: raspotify_audio_device != None
  notify:
    - restart raspotify
